### ISSUE TITLE
[support] what are proper fields for wordreference

### ISSUE THREAD

**Issue by omega3** [OoDeLally/anki-add-hooks-userscripts#26]
What are proper fields for wordreference? Now it shows me button. 
https://i.imgur.com/bmsaoSr.png

I chose basic note type. But it seems that meaning: (UK study before exam) and example sentence is outside of Front field

https://i.imgur.com/0hrp8DN.png

I would like to be able to make cloze from example sentence.

By the way would it be possible to get rid of formatting? Preferably all html, css formatting but in the first place " wordreference.com" and en, pl (language indication) in every card and every field. There is already tag wordreference.com and I don't need to have indication of language because I know it (unless someone learns meanings from two or more languages at the same time).

**Comment by OoDeLally** [comment]
> What are proper fields for wordreference? Now it shows me button.
> https://i.imgur.com/bmsaoSr.png

I don't understand your question. Can you be more specific?

> I chose basic note type. But it seems that meaning: (UK study before exam) and example sentence is outside of Front field
> 
> https://i.imgur.com/0hrp8DN.png

The card's html is badly rendered by the desktop app. I have the same issue here. But it renders fine when you actually revise the card, or on the mobile app. I believe this is a bug from the desktop app's browser, so there is nothing I can do here (make a push-request on their github?).

> 
> I would like to be able to make cloze from example sentence.

Can you describe how you would see that feature exactly?
The sentence blocks contain the information of which language they are written in. So a Polish sentence should be written on the Polish side of the card, and English sentence on the English side.
Do you mean you would like to create a extra separate card just for the sentence alone?

> By the way would it be possible to get rid of formatting? Preferably all html, css formatting but in the first place " wordreference.com" and en, pl (language indication) in every card and every field. There is already tag wordreference.com and I don't need to have indication of language because I know it (unless someone learns meanings from two or more languages at the same time).

Can I ask you why the formatting is a problem for you?
If you can program in JS, you can create your own custom hook, starting from mine, and modifying the parts that generate the card's content. It is not very hard.

**Comment by omega3** [comment]
> But it renders fine when you actually revise the card

Unfortunately not in my case:

This is strange but first example sentence is visible 
https://imgur.com/3oGEoCc
but in review mode is not visible
https://imgur.com/MAQv9JK
And after a while it disappears from browser mode view
https://imgur.com/5ciZ47S

And as you can see in the first screenshot it is not possible to create cloze because when I click on word that I want to wrap in cloze the Cloze function is inactive. This is because the example sentence is outside of Front field. Cloze function is active only when mouse coursor is whithin the field.

> Can I ask you why the formatting is a problem for you?

Maybe this is not a big problem, but it adds a lot of bits of data and when there is a lot of cards Anki database become big and slow, besides it distracts and I focus attention on irrelevant information insted on something to memorise. 

But the problem that example sentence is outside field is of primary importance to me.

**Comment by OoDeLally** [comment]
What app are you using? I am using anki desktop 2.1.11, and used the same page as yours (https://www.wordreference.com/enpl/revise).
The browser mode is badly-rendered, like your screenshot. However it renders fine on review mode:

![image](https://user-images.githubusercontent.com/1717629/57139460-994d5100-6db5-11e9-8aeb-0e506ecb4e4f.png)

**Comment by omega3** [comment]
I use 
Anki desktop version 2.1.12 (eef86bf3)
Qt 5.12.1 PyQt 5.11.3

Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.57.0
Qt Version: 5.12.3
Kernel Version: 5.0.9-2-MANJARO
OS Type: 64-bit

Chromium  74.0.3729.131 (Official version) Manjaro Linux (64-bit)

**Comment by OoDeLally** [comment]
Seems like indeed your card doesnt have the data inside.
Can you try deleting the card and adding it again from the site?
Maybe there was some bug I corrected since then.

**Comment by omega3** [comment]
I removed script and loaded it again and still have the same issue.
Here is my apkg file.

https://drive.google.com/open?id=12FY1UNSBj-N2Tp2ePP-VEnZyraA93YFg

**Comment by OoDeLally** [comment]
Could you reinstall the userscript with the following: https://pastebin.com/L0chhxee
And screenshot what the console says (F12) when you click on `Add` at https://www.wordreference.com/enpl/revise ?

Here is what mine says:

![image](https://user-images.githubusercontent.com/1717629/57245219-93b46d00-703a-11e9-8367-1f56e41b4f7d.png)


Thank you

**Comment by omega3** [comment]
https://imgur.com/OzDAPZ5

**Comment by OoDeLally** [comment]
Thank you.
And the final card doesn't contain the `revise for` string?
I find it hard to believe, since the card get this exact hmtl code.

**Comment by omega3** [comment]
> And the final card doesn't contain the revise for string?

It is strange, because right after adding card it contains revise for
https://imgur.com/eNcASet

But when I click within front field and after that in browser field the content disappears.

Click in area 1 and after that in area 2
and again on that card to see it.

**Comment by OoDeLally** [comment]
Interesting. It seems like it is anki's wysiwyg editor which reinterpret the html and rewrite it without the content....
Well in this case there is nothing much I can do... :/
I suggest you post an issue on anki desktop's repository.
Closing this, unless I can be of any help.

**Comment by OoDeLally** [comment]
I believe I solved the problem.
The wordreference display the `revise for` in a `<td>`. When I extract this node, the `<td>` gets out if it's `<table>`. For the review feature, it is fine, because it seems to use a native browser, which is tolerant to such html mistake. 
However the wysiwyg editor doesn't seem to like this inconsistency, and probably doesn't write it in its internal DOM. So when it rewrite the html code, you lose it.
I changed the script so it converts the `td` to a normal `div` and it seems like the editor likes it better.
I updated the scripts, so you can install the new version.
Please reopen the issue if you still have that problem.
